enum DuitElementType {
    row = "Row",
    column = "Column",
    center = "Center",
    sizedBox = "SizedBox",
    coloredBox = "ColoredBox",
    text = "Text",
    textField = "TextField",
    elevatedButton = "ElevatedButton",
    empty = "Empty",
    custom = "Custom",
    stack = "Stack",
    expanded = "Expanded",
    padding = "Padding",
    positioned = "Positioned",
    decoratedBox = "DecoratedBox",
    checkBox = "CheckBox",
    container = "Container",
    image = "Image",
    gestureDetector = "GestureDetector",
    align = "Align",
    transform = "Transform",
    richText = "RichText",
    wrap = "Wrap",
  }

export default DuitElementType;